### ISSUE TITLE
What addons do y'all use?

### ISSUE THREAD

**Issue by tilkinsc** [tilkinsc/KiwiItemInfo#7]
I am looking to enhance compatibility support with other addons.

Which addons do you use that doesn't work with this, or what are some addons you think are incompatible?

**Comment by idl0r** [comment]
https://wowinterface.com/downloads/info24976-MoncaiEquipmentCompareClassic.html perhaps.
I've both enabled right now and it seems to work, at the first glance at least. It also shows the comparison without having to hit shit or keep it pressed, which is a benefit.
Otherwise I don't think I've more that might be incompatible.

**Comment by tilkinsc** [comment]
`/kiwiii aci` enables shiftless item comparison

**Comment by tilkinsc** [comment]
Questie compatible
ProfessionItemTooltip compatible
Atlas* Compatible
